### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [lmotta/togglegroupvisibility#1]
The functionality described in the About seems already present in core QGIS.
Please clarify what the plugin is actually adding.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by lmotta** [comment]
Sorry for inconvenience.
I updated the metadata.
I hope so that it  more clarify the functionality of plugin.
Version 0.11

*Video: https://youtu.be/cbjHi6w7XnA
